### ISSUE TITLE
Help with Android older versions

### ISSUE THREAD

**Issue by plam50** [linkedin/LiTr#90] opened 2021-01-31 21:23 UTC
Hi

I have been using your library for a few weeks and its really good! I was wondering if under the hood you use any of the android libraries such as MediaMetaDataRetriever?

I am trying to use it to access certain properties about the videos and have completely hit a wall with it working under certain situations, I.e. works fine on
Api 28 but just returns null for api 24., but the docs seem to indicate the things I am trying work on versions > api 10.

Do you have any experience with things like this and suggestions potential avenues to debug? — I am starting to get desperate :(

**Comment by izzytwosheds** [comment] 2021-02-01 14:40
Hi!
We are happy that you are enjoying LiTr!
Under the hood LiTr uses `MediaCodec` APIs (https://developer.android.com/reference/android/media/MediaCodec) `MediaMetadataRetriever` is part of them, LiTr uses it in `MediaExtractorMediaSource` to get video rotation value. Which metadata are you trying to get? Did you try using `MediaExtractor`? It can be very useful to extract track metadata.

**Comment by plam50** [comment] 2021-02-01 21:47
Thanks for replying!

I managed to get it working on the emulator, turns out I was using a QuickTime file not an mp4, which doesn't seem to work on < 24. However, since switching to the mp4 file I now received an error during transcoding on my old Samsung Galaxy s5.

The video transcodes to around 99.98% but instead of completing it fires the onError callback with the following message

```
bufferInfo must specify a valid buffer offset, size and presentation time.
```

This isn’t happening on the emulator using the same android version (6.0 api 23). Do you have any ideas what could be causing this?

It also doesn’t seem to happen on any other devices (although they are a lot newer)

I am setting the following parameters

```
targetVideoFormat.setString(MediaFormat.KEY_MIME, MediaFormat.MIMETYPE_VIDEO_AVC);
targetVideoFormat.setInteger(MediaFormat.KEY_WIDTH, dimensions.get("width"));
targetVideoFormat.setInteger(MediaFormat.KEY_HEIGHT, dimensions.get("height"));
targetVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, videoBitrate);
targetVideoFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 5);
targetVideoFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 30);

audioVideoFormat.setString(MediaFormat.KEY_MIME, (String) getAudioTrackData(applicationContext, sourceURI, MediaFormat.KEY_MIME, MEDIA_TYPE.STRING));
audioVideoFormat.setInteger(MediaFormat.KEY_BIT_RATE, audioBitrate);
audioVideoFormat.setInteger(MediaFormat.KEY_SAMPLE_RATE, sampleRate);
audioVideoFormat.setInteger(MediaFormat.KEY_CHANNEL_COUNT, channel);

mediaTransformer = new MediaTransformer(applicationContext);


mediaTransformer.transform(processID,
sourceURI,
outputPath,
targetVideoFormat,
audioVideoFormat,
new TransformationListener() {


});
```

Do you have any ideas about what could be causing this.

**Comment by izzytwosheds** [comment] 2021-02-02 03:59
You are not trimming the video, right? 
I will look into this problem. Someone else was mentioning a similar issue earlier. Does this happen for all videos on Galaxy S5, or just that video?

**Comment by plam50** [comment] 2021-02-02 21:41
Hi 

No I haven’t trimmed the video, just changed the bitrate. It seems to be happening with all videos I provide to the Galaxy S5.  Does this seem like a big bug to fix or could it just be a small problem?

**Comment by izzytwosheds** [comment] 2021-02-02 23:08
I will have to fix this, this sounds like a recently introduced bug. I will look into this.

**Comment by plam50** [comment] 2021-02-05 20:24
Thanks so much if you want me to test any new versions or changes on my phone i am happy to do so :)

**Comment by izzytwosheds** [comment] 2021-02-06 03:48
I got my Galaxy S5, will try to debug on that. Will ask for your help with testing if I get stuck or can't reproduce the issue.

**Comment by izzytwosheds** [comment] 2021-02-08 00:01
Found the issue, fix is coming: https://github.com/linkedin/LiTr/pull/92

**Comment by plam50** [comment] 2021-02-08 20:33
thanks, looking forward to the fix :)

**Comment by izzytwosheds** [comment] 2021-02-09 01:11
Fix merged. Can you try to verify if it fixes the problem on your device?

**Comment by plam50** [comment] 2021-02-09 20:56
Hi 
Thank you so much for looking into this so quickly 

I tried to get it working in my app but it seems to break on all real devices, but works on the emulator still.
I think it could be related to how I have imported it (its not using a proper release so I think I may be missing dependencies) 
I did this 
```
maven {
    url "https://jitpack.io"
}

dependencies {
    implementation 'com.github.linkedin:LiTr:master-SNAPSHOT'
}
```
However I cloned your full repo and ran the example on my Samsung and it seems to be working fine. 

If you do a release with a tag I am happy to test it using that unless you have a better way to import the master branch in gradle (sorry not an expert with gradle)

**Comment by izzytwosheds** [comment] 2021-02-09 21:48
I didn't realize you were testing it with your app. I will cut a release, so you can test in your app. I thought you were testing with LiTr demo app, and wanted to make sure that issue was fixed on your device before I cut a new release.

**Closed** 2021-02-09 21:53 UTC

**Comment by plam50** [comment] 2021-02-10 20:13
thanks a lot its working great
