### ISSUE TITLE
Trimming video in some devices faces fdsan errors

### ISSUE THREAD

**Issue by tianshangaimi12** [linkedin/LiTr#151] opened 2021-12-30 09:20 UTC
Trimming video is succeed, but after a while the app become stuck.The log reports a lot of fdsan and file descriptor errors.

Here is the code:
` TransformationOptions transformationOptions = new TransformationOptions.Builder()                    .setGranularity(MediaTransformer.GRANULARITY_DEFAULT)                   
 .setSourceMediaRange(mediaRange)                    .build();
mMediaTransformer.transform(lastRequestId, Uri.parse(videoPathInput), videoPlayUrl,getVideoFormat(), null,listener,transformationOptions);`

Here is the log:
E/fdsan: failed to exchange ownership of file descriptor: fd 146 is owned by FILE* 0x76a2c1d970, was expected to be unowned
E/fdsan: attempted to close file descriptor 133, expected to be unowned, actually owned by FILE* 0x76a2c1d710
E/fdsan: attempted to close file descriptor 146, expected to be owned by unique_fd 0x76a83e16dc, actually owned by FILE* 0x76a2c1d970.

Thanks.

**Comment by izzytwosheds** [comment] 2022-01-03 16:29
Thank you for reporting this!
Is this happening with all videos or a specific video? Does this happen with no trimming? Which device/OS is this happening on?

**Comment by tianshangaimi12** [comment] 2022-01-04 02:05
This is happening on some Huawei phones(Android 11 and Android 10) with all videos.

**Comment by RishabJaiswal** [comment] 2022-03-15 10:21
I am guessing that this might be due to file systems changes introduced in Android10 & on. Now we have to user Storage Access Framework or media store APIs to make changes to a file.

**Comment by izzytwosheds** [comment] 2022-03-25 19:53
@RishabJaiswal I think you are right, this looks like something that could be caused by scoped storage. 
@tianshangaimi12 there is an incoming PR that adds support for target Uri instead of a target file path, it should help with scoped storage issues. Alternatively, you can also use `transform(List<TrackTransform>)` API and use a `MediaMuxerTarget` constructor that accepts a `Uri`

**Comment by tianshangaimi12** [comment] 2022-03-29 08:11
@izzytwosheds Thanks for your reply.I use transform(List<TrackTransform>) API  and use Uri instead of path, the Huawei phone gets the same result.
I find it only happens on it's screen shot video, but other devices uses the same video is ok.

**Comment by izzytwosheds** [comment] 2022-03-29 23:42
That is an interesting use case. Screenshot video on a specific device? And camera videos are ok? And same video is ok on other devices?

**Comment by tianshangaimi12** [comment] 2022-03-30 02:31
Camera videos and network videos are ok, only the device's screen shot video can cause the problem.
The same video is ok on other devices, and other device's screen shot video is also good on the Huawei phones.
I have tested on 3 Huawei phones(above android 10), they all have the problem.

**Comment by tianshangaimi12** [comment] 2022-08-10 08:39
I upgrade the library version to 1.5.0, the problem is solved.Thanks.

**Comment by izzytwosheds** [comment] 2022-08-10 11:45
That is great! I will close the issue for now. Let me know if you see any other problems.

**Closed by izzytwosheds** 2022-08-10 11:45 UTC
