### ISSUE TITLE
Rendering broken on Samsung Galaxy 7 Edge

### ISSUE THREAD

**Issue by theseafaringturtle** [linkedin/LiTr#7] opened 2019-12-18 13:45 UTC
There seems to be an issue with rotation on this specific phone. Videos are cut halfway in portrait mode, and they're upside down in landscape right mode.
Every other device works as it should, including the Samsung Galaxy 8.

**Comment by izzytwosheds** [comment] 2019-12-18 13:57
Nice find! We will look into this right away. Thanks for reporting this!

**Comment by izzytwosheds** [comment] 2019-12-18 16:41
Was the video captured on that phone?

**Comment by IanField90** [comment] 2019-12-18 17:05
Hi @izzytwosheds ,
Yes it was captured originally on the S7 Edge. We're just taking a look now to see if the S7-captured video behaves as expected on known working devices to narrow down if it's a bad input video, or a device-specific filter/compatibility issue.

**Comment by IanField90** [comment] 2019-12-18 17:33
Update:
We've determined it's the device's processing specifically which produces this.

Example output (not real resolution, input is 720 x 1280):
<img width="668" alt="Expected output" src="https://user-images.githubusercontent.com/159527/71109027-4c8b7e80-21bc-11ea-8450-3f269c1c18dc.png">

<img width="1392" alt="Actual output" src="https://user-images.githubusercontent.com/159527/71109041-54e3b980-21bc-11ea-9f0c-cc35c4edcdac.png">

I've needed to omit some of the overlay content, but in the actual output it stretched, but in the same orientation as the video itself, which I've tried to illustrate by adding annotations/text.

**Comment by izzytwosheds** [comment] 2019-12-18 17:46
Is the output broken if overlays are not applied?

**Comment by IanField90** [comment] 2019-12-18 18:02
Just tried that out, yes it is.

<img width="1392" alt="no overlay Output" src="https://user-images.githubusercontent.com/159527/71110923-27007400-21c0-11ea-9792-34e820902c0f.png">

Further information:
Lib version is 1.1.0. So #5 has been retro-fitted/worked around. Which is a workaround that works on other devices including S8,  Pixel 1, 3, 4. (1.1.1 is not available on Bintray)
(https://github.com/linkedin/LiTr/commit/2e91d84880916be607c38c4207afc9dda7a2f357)

**Comment by izzytwosheds** [comment] 2019-12-18 18:08
1.1.1 should be available on Bintray: https://bintray.com/beta/#/linkedin/maven/litr-filters/1.1.1?tab=overview It should only apply to vertical scaling of overlays, not affect the entire video frame, though. 
What happens if you process the problematic video shot on GS7 Edge on a GS8? 

What is the model number of your GS7 Edge and which version of Android is it running? I will try to get ahold of one...

**Comment by izzytwosheds** [comment] 2019-12-18 20:30
We could not reproduce it on GS7 Edge. Can you guys try using LiTr demo app on your device and see if the issue persists?

**Comment by IanField90** [comment] 2019-12-18 21:00
Apologies, I see it on Bintray now, thanks. I was looking at the page for `litr` rather than the `litr-filters`.

>What happens if you process the problematic video shot on GS7 Edge on a GS8?

The video outputs as we expect if a video captured on GS7 Edge is processed on GS8.

>Can you guys try using LiTr demo app on your device and see if the issue persists?

This works okay, for the same input video too:

<img width="624" alt="litr-demo output" src="https://user-images.githubusercontent.com/159527/71122423-76529e80-21d8-11ea-94ba-66f6ce89e0ab.png">

![device-info](https://user-images.githubusercontent.com/159527/71122690-190b1d00-21d9-11ea-9ae7-2b64de32a026.png)

Model number: `SM-G935F`

Thanks very much for your help with this. We'll do some more debugging our side and hopefully update for you. This is unlikely to be before the new year though. Definitely a strange one given it's behaving fine on other devices!

**Comment by izzytwosheds** [comment] 2019-12-18 21:15
In the near future I will probably sync up versions for all LiTr libraries. We will publish duplicates, but there will be no confusion. 

So using LiTr demo app works on GS7 Edge, too?

Keep me posted! Happy to help out.

**Comment by IanField90** [comment] 2019-12-20 11:42
That's right, the demo app worked fine on GS7 Edge.
We've sorted it on our side. We were adding setting the output format rotation from the input format, which wasn't necessary.

I'd suggest we close this issue 😄

**Comment by izzytwosheds** [comment] 2019-12-20 12:09
Great. Thanks for sorting this out.

**Closed** 2019-12-20 12:09 UTC
